name: na-cordex-viz-cookbook-dev
channels:
- conda-forge
dependencies:
- bottleneck
- cftime>=1.0.4.2
- dask>=2023.4.0
- dask-jobqueue>=0.8.1
- dask-gateway
- distributed
- s3fs
- intake>=0.6.8
- intake-esm>=2020.8.15
- ipykernel
- matplotlib
- nc-time-axis
- pip
- pytest
- python<=3.11
- tqdm
- watermark
- xarray>=2023.4.2
# For Pythia cookbook-related builds
- jupyter-book
- jupyterlab
- jupyter_server
- sphinx-pythia-theme
